[ja]
contentdir = "content/ja"
languageName = "日本語"
title = "blog.aiandrox"
weight = 1

[en]
contentdir = "content/en"
languageName = "English"
languagedir = "ltr"
title = "Hugo Zzo Theme"
weight = 2

[ko]
contentdir = "content/ko"
languageName = "한국어"
languagedir = "ltr"
title = "Hugo Zzo Theme"
weight = 3
